### ISSUE TITLE
CJK characters are unsupported

### ISSUE THREAD

**Issue by raehik** [saleemrashid/is-this-a-pigeon#1]
* [Input tweet](https://twitter.com/raehik/status/1000718331324837888)
  * [Output tweet](https://twitter.com/this_pigeon/status/1000718340590133248)
  * Expected: "Is this これは日本語ですか？"
  * Result: "Is this (unicode not-found characters)"

You already said on Twitter that you could fix it by adding CJK fonts but this way I get to add to your inbox :)

Optionally, further support for other languages could be added by trying to match the start of a tweet to a given string. i.e. これは may indicate "is this" in Japanese (it's the start of the original line).

**Comment by saleemrashid** [comment]
> (unicode not-found characters)

Also known as "tofu"!

> further support for other languages could be added by trying to match the start of a tweet

Perhaps, but I would likely keep the "Is this" in English (from the image I'm using) and just remove the equivalent Japanese phrase from the start of the input. Maybe worth creating a new issue for this?

**Comment by raehik** [comment]
Yeah that's what I meant. I won't make a new issue because to get the line proper, it should be "これは……ですか？" and it's getting too complex by then.
